export const SIGNUP = "SIGNUP";
export const LOGIN = "LOGIN";
export const LOGIN_WITH_FACEBOOK = "LOGIN_WITH_FACEBOOK";
export const VERIFY_TOKEN = "VERIFY_TOKEN";

export const GET_TEMPLATES = "GET_TEMPLATES";

export const INIT_BUILDER = "INIT_BUILDER";

export const CREATE_ARTIST_BY_SPOTIFY = "CREATE_ARTIST_BY_SPOTIFY";
export const ADD_WEBSITE_URL = "ADD_WEBSITE_URL";
export const SEARCH_ARTISTS_BY_NAME = "SEARCH_ARTISTS_BY_NAME";
export const SELECT_ARTIST = "SELECT_ARTIST";

export const GET_SOCIAL_DATA = "GET_SOCIAL_DATA";
export const ADD_SOCIAL_URL = "ADD_SOCIAL_URL";
export const UPDATE_SOCIAL_URL = "UPDATE_SOCIAL_URL";

export const GET_WEB_BUILDER = "GET_WEB_BUILDER";
export const CREATE_WEB_BUILDER = "CREATE_WEB_BUILDER";
export const UPDATE_WEB_BUILDER = "UPDATE_WEB_BUILDER";

export const GET_WEBSITE_COVER = "GET_WEBSITE_COVER";
export const UPDATE_WEBSITE_COVER = "UPDATE_WEBSITE_COVER";

export const UPDATE_USER = "UPDATE_USER";
export const GET_ARTISTS = "GET_ARTISTS";
export const UPDATE_ARTIST_SOCIAL_TOKEN = "UPDATE_ARTIST_SOCIAL_TOKEN";

export const GENERATE_WEBSITE = "GENERATE_WEBSITE";
